### PR TITLE
Instead of automatically downloading the war file use one that is mou…

### PR DESCRIPTION
**Pull request by KieranFrance**
Scripted updated to use mounted war instead of downloading one.

### CODE REVIEW

**Comment by leonatherton** [comment]
@KieranFrance I noticed a couple of things

1. ACCESS_USERNAME/ACCESS_PASSWORD have been renamed to BUILDVU_USER/BUILDVU_PASSWORD, was that intended?
2. It looks like the change forces authentication to be used, was that intended?
3. The templating stuff has been partially removed

It looks like it's possible you were not on latest version and did not have this change? https://github.com/idrsolutions/buildvu-docker/commit/ce99cb1699f81ab9784acbd23ab66a00edab2400

**Comment by KieranFrance** [comment]
Looks like you are right, I'll rework this change.

**Comment by KieranFrance** [comment]
I have updated the script to ensure it is up to date

**Comment by leonatherton** [comment]
@KieranFrance looks good now.

Only adjustment I would suggest is to add https://docs.idrsolutions.com/buildvu/docker-deployment/ to the error message as that will be the message the user sees whether running locally or via a cloud platform.

**Comment by KieranFrance** [comment]
Good point. I have updated.

**Review by daniel-warren — APPROVED** [review]
Changes look good

**Review by leonatherton — APPROVED** [review]

**Pull request merged**
